import { createPushupAnalyzer } from './pushupAnalyzer.js'
import { createCurlAnalyzer } from './curlAnalyzer.js'
import { createLateralRaiseAnalyzer } from './lateralRaiseAnalyzer.js'
import { createSquatAnalyzer } from './squatAnalyzer.js'
import { createLungeAnalyzer } from './lungeAnalyzer.js'
import { createCalfRaiseAnalyzer } from './calfRaiseAnalyzer.js'
import { createJackAnalyzer } from './jackAnalyzer.js'
import { createHighKneeAnalyzer } from './highKneeAnalyzer.js'
import { createPushupKneesAnalyzer } from './pushupKneesAnalyzer.js'
import { createPushupWideAnalyzer } from './pushupWideAnalyzer.js'
import { createPushupDiamondAnalyzer } from './pushupDiamondAnalyzer.js'
import { createPushupInclineAnalyzer } from './pushupInclineAnalyzer.js'
import { createPushupDeclineAnalyzer } from './pushupDeclineAnalyzer.js'
import { createPikePushupAnalyzer } from './pikePushupAnalyzer.js'
import { createBenchPressAnalyzer } from './benchPressAnalyzer.js'
import { createInclinePressAnalyzer } from './inclinePressAnalyzer.js'
import { createBenchDipAnalyzer } from './benchDipAnalyzer.js'
import { createDipParallelAnalyzer } from './dipParallelAnalyzer.js'
import { createCurlHammerAnalyzer } from './curlHammerAnalyzer.js'
import { createCurlAlternateAnalyzer } from './curlAlternateAnalyzer.js'
import { createCurlConcentrationAnalyzer } from './curlConcentrationAnalyzer.js'
import { createFrontRaiseAnalyzer } from './frontRaiseAnalyzer.js'
import { createRearDeltFlyAnalyzer } from './rearDeltFlyAnalyzer.js'
import { createShoulderPressAnalyzer } from './shoulderPressAnalyzer.js'
import { createArnoldPressAnalyzer } from './arnoldPressAnalyzer.js'
import { createUprightRowAnalyzer } from './uprightRowAnalyzer.js'
import { createLatPulldownAnalyzer } from './latPulldownAnalyzer.js'
import { createPullupAnalyzer } from './pullupAnalyzer.js'
import { createChinupAnalyzer } from './chinupAnalyzer.js'
import { createSeatedRowAnalyzer } from './seatedRowAnalyzer.js'
import { createBentRowAnalyzer } from './bentRowAnalyzer.js'
import { createSingleArmRowAnalyzer } from './singleArmRowAnalyzer.js'
import { createInvertedRowAnalyzer } from './invertedRowAnalyzer.js'
import { createFacePullAnalyzer } from './facePullAnalyzer.js'
import { createTricepsPushdownAnalyzer } from './tricepsPushdownAnalyzer.js'
import { createTricepsOverheadAnalyzer } from './tricepsOverheadAnalyzer.js'
import { createSkullcrusherAnalyzer } from './skullcrusherAnalyzer.js'
import { createTricepsKickbackAnalyzer } from './tricepsKickbackAnalyzer.js'
import { createSquatSumoAnalyzer } from './squatSumoAnalyzer.js'
import { createSquatGobletAnalyzer } from './squatGobletAnalyzer.js'
import { createSquatJumpAnalyzer } from './squatJumpAnalyzer.js'
import { createSquatPistolAnalyzer } from './squatPistolAnalyzer.js'
import { createSquatCossackAnalyzer } from './squatCossackAnalyzer.js'
import { createSquatBulgarianAnalyzer } from './squatBulgarianAnalyzer.js'
import { createLungeReverseAnalyzer } from './lungeReverseAnalyzer.js'
import { createLungeLateralAnalyzer } from './lungeLateralAnalyzer.js'
import { createLungeWalkingAnalyzer } from './lungeWalkingAnalyzer.js'
import { createStepUpAnalyzer } from './stepUpAnalyzer.js'
import { createCalfRaiseSeatedAnalyzer } from './calfRaiseSeatedAnalyzer.js'
import { createDeadliftAnalyzer } from './deadliftAnalyzer.js'
import { createDeadliftRdlAnalyzer } from './deadliftRdlAnalyzer.js'
import { createDeadliftSingleLegAnalyzer } from './deadliftSingleLegAnalyzer.js'
import { createGoodMorningAnalyzer } from './goodMorningAnalyzer.js'
import { createHipThrustAnalyzer } from './hipThrustAnalyzer.js'
import { createGluteBridgeAnalyzer } from './gluteBridgeAnalyzer.js'
import { createLegPressAnalyzer } from './legPressAnalyzer.js'
import { createLegExtensionAnalyzer } from './legExtensionAnalyzer.js'
import { createLegCurlAnalyzer } from './legCurlAnalyzer.js'
import { createDonkeyKickAnalyzer } from './donkeyKickAnalyzer.js'
import { createFireHydrantAnalyzer } from './fireHydrantAnalyzer.js'
import { createSideLegRaiseAnalyzer } from './sideLegRaiseAnalyzer.js'
import { createHipAbductionAnalyzer } from './hipAbductionAnalyzer.js'
import { createButtKicksAnalyzer } from './buttKicksAnalyzer.js'
import { createMountainClimberAnalyzer } from './mountainClimberAnalyzer.js'
import { createBurpeeAnalyzer } from './burpeeAnalyzer.js'
import { createSkaterJumpAnalyzer } from './skaterJumpAnalyzer.js'
import { createSealJackAnalyzer } from './sealJackAnalyzer.js'
import { createCrunchAnalyzer } from './crunchAnalyzer.js'
import { createSitupAnalyzer } from './situpAnalyzer.js'
import { createBicycleCrunchAnalyzer } from './bicycleCrunchAnalyzer.js'
import { createLegRaiseAnalyzer } from './legRaiseAnalyzer.js'
import { createFlutterKickAnalyzer } from './flutterKickAnalyzer.js'
import { createVUpAnalyzer } from './vUpAnalyzer.js'
import { createRussianTwistAnalyzer } from './russianTwistAnalyzer.js'
import { createToeTouchAnalyzer } from './toeTouchAnalyzer.js'
import { createDeadBugAnalyzer } from './deadBugAnalyzer.js'
import { createBirdDogAnalyzer } from './birdDogAnalyzer.js'
import { createSupermanAnalyzer } from './supermanAnalyzer.js'
import { createSideBendAnalyzer } from './sideBendAnalyzer.js'
import { createPecDeckAnalyzer } from './pecDeckAnalyzer.js'
import { createDumbbellFlyAnalyzer } from './dumbbellFlyAnalyzer.js'
import { createShrugAnalyzer } from './shrugAnalyzer.js'
import { createPunchCrossAnalyzer } from './punchCrossAnalyzer.js'
import { createJumpRopeAnalyzer } from './jumpRopeAnalyzer.js'
import { createPlankAnalyzer } from './plankAnalyzer.js'
import { createPlankForearmAnalyzer } from './plankForearmAnalyzer.js'
import { createPlankSideAnalyzer } from './plankSideAnalyzer.js'
import { createPlankReverseAnalyzer } from './plankReverseAnalyzer.js'
import { createHollowHoldAnalyzer } from './hollowHoldAnalyzer.js'
import { createWallSitAnalyzer } from './wallSitAnalyzer.js'
import { createSquatHoldAnalyzer } from './squatHoldAnalyzer.js'
import { createGluteBridgeHoldAnalyzer } from './gluteBridgeHoldAnalyzer.js'
import { createDeadHangAnalyzer } from './deadHangAnalyzer.js'
import { createChinHoldAnalyzer } from './chinHoldAnalyzer.js'
import { createSupermanHoldAnalyzer } from './supermanHoldAnalyzer.js'
import { createBirdDogHoldAnalyzer } from './birdDogHoldAnalyzer.js'
import { createBoatPoseAnalyzer } from './boatPoseAnalyzer.js'
import { createLSitAnalyzer } from './lSitAnalyzer.js'
import { createChairPoseAnalyzer } from './chairPoseAnalyzer.js'
import { createStHamstringAnalyzer } from './stHamstringAnalyzer.js'
import { createStQuadAnalyzer } from './stQuadAnalyzer.js'
import { createStCalfWallAnalyzer } from './stCalfWallAnalyzer.js'
import { createStHipFlexorAnalyzer } from './stHipFlexorAnalyzer.js'
import { createStPigeonAnalyzer } from './stPigeonAnalyzer.js'
import { createStFigure4Analyzer } from './stFigure4Analyzer.js'
import { createStButterflyAnalyzer } from './stButterflyAnalyzer.js'
import { createStFrogAnalyzer } from './stFrogAnalyzer.js'
import { createStCobraAnalyzer } from './stCobraAnalyzer.js'
import { createStChildsPoseAnalyzer } from './stChildsPoseAnalyzer.js'
import { createStCatCowAnalyzer } from './stCatCowAnalyzer.js'
import { createStDowndogAnalyzer } from './stDowndogAnalyzer.js'
import { createStShoulderCrossAnalyzer } from './stShoulderCrossAnalyzer.js'
import { createStTricepsAnalyzer } from './stTricepsAnalyzer.js'
import { createStChestDoorAnalyzer } from './stChestDoorAnalyzer.js'
import { createStLatAnalyzer } from './stLatAnalyzer.js'
import { createStNeckSideAnalyzer } from './stNeckSideAnalyzer.js'
import { createStSpinalTwistAnalyzer } from './stSpinalTwistAnalyzer.js'
import { createStSideBendAnalyzer } from './stSideBendAnalyzer.js'
import { createStStandingForwardAnalyzer } from './stStandingForwardAnalyzer.js'
import { createWuArmCirclesAnalyzer } from './wuArmCirclesAnalyzer.js'
import { createWuHipCirclesAnalyzer } from './wuHipCirclesAnalyzer.js'
import { createWuTorsoTwistAnalyzer } from './wuTorsoTwistAnalyzer.js'
import { createWuLegSwingAnalyzer } from './wuLegSwingAnalyzer.js'
import { createWuInchwormAnalyzer } from './wuInchwormAnalyzer.js'
import { createWuWorldsGreatestAnalyzer } from './wuWorldsGreatestAnalyzer.js'
import { createWuShoulderDislocateAnalyzer } from './wuShoulderDislocateAnalyzer.js'
import { createWuMarchAnalyzer } from './wuMarchAnalyzer.js'
import { createBalSingleLegAnalyzer } from './balSingleLegAnalyzer.js'
import { createBalTreeAnalyzer } from './balTreeAnalyzer.js'
import { createBalWarrior3Analyzer } from './balWarrior3Analyzer.js'
import { createBalStandingQuadAnalyzer } from './balStandingQuadAnalyzer.js'

export const EXERCISE_CATEGORIES = {
  A: 'Brazos, pecho, hombros y espalda',
  B: 'Piernas, glúteos y cadera',
  C: 'Cardio y core',
  D: 'Isometría',
  E: 'Estiramientos',
  F: 'Calentamiento y movilidad',
  G: 'Equilibrio',
}

export const EXERCISE_TYPES = {
  reps: 'reps',
  tiempo: 'tiempo',
}

export const EXERCISE_STATUS = {
  implementado: 'implementado',
  en_progreso: 'en_progreso',
  pendiente: 'pendiente',
}

const IMPLEMENTED_ANALYZERS = {
  pushup: createPushupAnalyzer,
  curl_biceps: createCurlAnalyzer,
  lateral_raise: createLateralRaiseAnalyzer,
  squat: createSquatAnalyzer,
  lunge: createLungeAnalyzer,
  calf_raise: createCalfRaiseAnalyzer,
  jumping_jack: createJackAnalyzer,
  high_knees: createHighKneeAnalyzer,
}

export const EXERCISE_REGISTRY = [
  {
    id: 'pushup',
    nombre: 'Flexiones de pecho',
    categoria: 'A',
    musculos: ['pecho', 'tríceps', 'hombros'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createPushupAnalyzer,
  },
  {
    id: 'pushup_knees',
    nombre: 'Flexiones con rodillas apoyadas',
    categoria: 'A',
    musculos: ['pecho', 'tríceps', 'hombros'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createPushupKneesAnalyzer,
  },
  {
    id: 'pushup_wide',
    nombre: 'Flexiones abiertas',
    categoria: 'A',
    musculos: ['pecho', 'hombros'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createPushupWideAnalyzer,
  },
  {
    id: 'pushup_diamond',
    nombre: 'Flexiones diamante',
    categoria: 'A',
    musculos: ['tríceps', 'pecho'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createPushupDiamondAnalyzer,
  },
  {
    id: 'pushup_incline',
    nombre: 'Flexiones inclinadas',
    categoria: 'A',
    musculos: ['pecho', 'hombros'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createPushupInclineAnalyzer,
  },
  {
    id: 'pushup_decline',
    nombre: 'Flexiones declinadas',
    categoria: 'A',
    musculos: ['pecho', 'hombros'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createPushupDeclineAnalyzer,
  },
  {
    id: 'pike_pushup',
    nombre: 'Flexiones pike',
    categoria: 'A',
    musculos: ['hombros', 'tríceps'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createPikePushupAnalyzer,
  },
  {
    id: 'bench_press',
    nombre: 'Press de banca',
    categoria: 'A',
    musculos: ['pecho', 'tríceps', 'hombros'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createBenchPressAnalyzer,
  },
  {
    id: 'incline_press',
    nombre: 'Press inclinado con mancuernas',
    categoria: 'A',
    musculos: ['pecho', 'hombros'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createInclinePressAnalyzer,
  },
  {
    id: 'bench_dip',
    nombre: 'Fondos en banco',
    categoria: 'A',
    musculos: ['tríceps', 'pecho'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createBenchDipAnalyzer,
  },
  {
    id: 'dip_parallel',
    nombre: 'Fondos en paralelas',
    categoria: 'A',
    musculos: ['pecho', 'tríceps'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createDipParallelAnalyzer,
  },
  {
    id: 'curl_biceps',
    nombre: 'Curl de bíceps',
    categoria: 'A',
    musculos: ['bíceps'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createCurlAnalyzer,
  },
  {
    id: 'curl_hammer',
    nombre: 'Curl martillo',
    categoria: 'A',
    musculos: ['bíceps', 'antebrazo'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createCurlHammerAnalyzer,
  },
  {
    id: 'curl_alternate',
    nombre: 'Curl alterno',
    categoria: 'A',
    musculos: ['bíceps'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: true,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createCurlAlternateAnalyzer,
  },
  {
    id: 'curl_concentration',
    nombre: 'Curl concentrado',
    categoria: 'A',
    musculos: ['bíceps'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createCurlConcentrationAnalyzer,
  },
  {
    id: 'lateral_raise',
    nombre: 'Elevaciones laterales',
    categoria: 'A',
    musculos: ['hombros'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createLateralRaiseAnalyzer,
  },
  {
    id: 'front_raise',
    nombre: 'Elevaciones frontales',
    categoria: 'A',
    musculos: ['hombros'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createFrontRaiseAnalyzer,
  },
  {
    id: 'rear_delt_fly',
    nombre: 'Pájaros',
    categoria: 'A',
    musculos: ['hombros', 'espalda'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createRearDeltFlyAnalyzer,
  },
  {
    id: 'shoulder_press',
    nombre: 'Press militar',
    categoria: 'A',
    musculos: ['hombros', 'tríceps'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createShoulderPressAnalyzer,
  },
  {
    id: 'arnold_press',
    nombre: 'Press Arnold',
    categoria: 'A',
    musculos: ['hombros', 'tríceps'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createArnoldPressAnalyzer,
  },
  {
    id: 'upright_row',
    nombre: 'Remo al mentón',
    categoria: 'A',
    musculos: ['hombros', 'trapecio'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createUprightRowAnalyzer,
  },
  {
    id: 'lat_pulldown',
    nombre: 'Jalón al pecho',
    categoria: 'A',
    musculos: ['dorsales', 'bíceps'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createLatPulldownAnalyzer,
  },
  {
    id: 'pullup',
    nombre: 'Dominadas',
    categoria: 'A',
    musculos: ['dorsales', 'bíceps'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createPullupAnalyzer,
  },
  {
    id: 'chinup',
    nombre: 'Dominadas supinas',
    categoria: 'A',
    musculos: ['dorsales', 'bíceps'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createChinupAnalyzer,
  },
  {
    id: 'seated_row',
    nombre: 'Remo sentado en polea',
    categoria: 'A',
    musculos: ['dorsales', 'bíceps'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createSeatedRowAnalyzer,
  },
  {
    id: 'bent_row',
    nombre: 'Remo con barra',
    categoria: 'A',
    musculos: ['dorsales', 'bíceps'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createBentRowAnalyzer,
  },
  {
    id: 'single_arm_row',
    nombre: 'Remo a una mano',
    categoria: 'A',
    musculos: ['dorsales', 'bíceps'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: true,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createSingleArmRowAnalyzer,
  },
  {
    id: 'inverted_row',
    nombre: 'Remo invertido',
    categoria: 'A',
    musculos: ['dorsales', 'bíceps'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createInvertedRowAnalyzer,
  },
  {
    id: 'face_pull',
    nombre: 'Face pull',
    categoria: 'A',
    musculos: ['hombros', 'espalda'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createFacePullAnalyzer,
  },
  {
    id: 'triceps_pushdown',
    nombre: 'Extensión de tríceps en polea',
    categoria: 'A',
    musculos: ['tríceps'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createTricepsPushdownAnalyzer,
  },
  {
    id: 'triceps_overhead',
    nombre: 'Extensión de tríceps sobre la cabeza',
    categoria: 'A',
    musculos: ['tríceps'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createTricepsOverheadAnalyzer,
  },
  {
    id: 'skullcrusher',
    nombre: 'Press francés',
    categoria: 'A',
    musculos: ['tríceps'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createSkullcrusherAnalyzer,
  },
  {
    id: 'triceps_kickback',
    nombre: 'Patada de tríceps',
    categoria: 'A',
    musculos: ['tríceps'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createTricepsKickbackAnalyzer,
  },
  {
    id: 'squat',
    nombre: 'Sentadilla',
    categoria: 'B',
    musculos: ['cuádriceps', 'glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createSquatAnalyzer,
  },
  {
    id: 'squat_sumo',
    nombre: 'Sentadilla sumo',
    categoria: 'B',
    musculos: ['glúteos', 'aductores'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createSquatSumoAnalyzer,
  },
  {
    id: 'squat_goblet',
    nombre: 'Sentadilla goblet',
    categoria: 'B',
    musculos: ['cuádriceps', 'glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createSquatGobletAnalyzer,
  },
  {
    id: 'squat_jump',
    nombre: 'Sentadilla con salto',
    categoria: 'B',
    musculos: ['cuádriceps', 'glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createSquatJumpAnalyzer,
  },
  {
    id: 'squat_pistol',
    nombre: 'Sentadilla a una pierna',
    categoria: 'B',
    musculos: ['cuádriceps', 'glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: true,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createSquatPistolAnalyzer,
  },
  {
    id: 'squat_cossack',
    nombre: 'Sentadilla cosaca',
    categoria: 'B',
    musculos: ['glúteos', 'aductores'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createSquatCossackAnalyzer,
  },
  {
    id: 'squat_bulgarian',
    nombre: 'Sentadilla búlgara',
    categoria: 'B',
    musculos: ['cuádriceps', 'glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: true,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createSquatBulgarianAnalyzer,
  },
  {
    id: 'lunge',
    nombre: 'Zancadas',
    categoria: 'B',
    musculos: ['cuádriceps', 'glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createLungeAnalyzer,
  },
  {
    id: 'lunge_reverse',
    nombre: 'Zancada hacia atrás',
    categoria: 'B',
    musculos: ['glúteos', 'cuádriceps'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createLungeReverseAnalyzer,
  },
  {
    id: 'lunge_lateral',
    nombre: 'Zancada lateral',
    categoria: 'B',
    musculos: ['glúteos', 'aductores'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createLungeLateralAnalyzer,
  },
  {
    id: 'lunge_walking',
    nombre: 'Zancadas caminando',
    categoria: 'B',
    musculos: ['cuádriceps', 'glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createLungeWalkingAnalyzer,
  },
  {
    id: 'step_up',
    nombre: 'Subida al cajón',
    categoria: 'B',
    musculos: ['cuádriceps', 'glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStepUpAnalyzer,
  },
  {
    id: 'calf_raise',
    nombre: 'Elevación de pantorrillas',
    categoria: 'B',
    musculos: ['pantorrillas'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createCalfRaiseAnalyzer,
  },
  {
    id: 'calf_raise_seated',
    nombre: 'Pantorrillas sentado',
    categoria: 'B',
    musculos: ['pantorrillas'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createCalfRaiseSeatedAnalyzer,
  },
  {
    id: 'deadlift',
    nombre: 'Peso muerto convencional',
    categoria: 'B',
    musculos: ['espalda', 'glúteos', 'isquiotibiales'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createDeadliftAnalyzer,
  },
  {
    id: 'deadlift_rdl',
    nombre: 'Peso muerto rumano',
    categoria: 'B',
    musculos: ['isquiotibiales', 'glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createDeadliftRdlAnalyzer,
  },
  {
    id: 'deadlift_single_leg',
    nombre: 'Peso muerto a una pierna',
    categoria: 'B',
    musculos: ['isquiotibiales', 'glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: true,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createDeadliftSingleLegAnalyzer,
  },
  {
    id: 'good_morning',
    nombre: 'Buenos días',
    categoria: 'B',
    musculos: ['isquiotibiales', 'espalda'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createGoodMorningAnalyzer,
  },
  {
    id: 'hip_thrust',
    nombre: 'Empuje de cadera',
    categoria: 'B',
    musculos: ['glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createHipThrustAnalyzer,
  },
  {
    id: 'glute_bridge',
    nombre: 'Puente de glúteos',
    categoria: 'B',
    musculos: ['glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createGluteBridgeAnalyzer,
  },
  {
    id: 'leg_press',
    nombre: 'Prensa de piernas',
    categoria: 'B',
    musculos: ['cuádriceps', 'glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createLegPressAnalyzer,
  },
  {
    id: 'leg_extension',
    nombre: 'Extensión de cuádriceps',
    categoria: 'B',
    musculos: ['cuádriceps'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createLegExtensionAnalyzer,
  },
  {
    id: 'leg_curl',
    nombre: 'Curl femoral',
    categoria: 'B',
    musculos: ['isquiotibiales'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createLegCurlAnalyzer,
  },
  {
    id: 'donkey_kick',
    nombre: 'Patada de glúteo',
    categoria: 'B',
    musculos: ['glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: true,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createDonkeyKickAnalyzer,
  },
  {
    id: 'fire_hydrant',
    nombre: 'Hidrante',
    categoria: 'B',
    musculos: ['glúteos'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: true,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createFireHydrantAnalyzer,
  },
  {
    id: 'side_leg_raise',
    nombre: 'Elevación lateral de pierna',
    categoria: 'B',
    musculos: ['glúteos'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: true,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createSideLegRaiseAnalyzer,
  },
  {
    id: 'hip_abduction',
    nombre: 'Abducción de cadera',
    categoria: 'B',
    musculos: ['glúteos'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createHipAbductionAnalyzer,
  },
  {
    id: 'jumping_jack',
    nombre: 'Polichinelas',
    categoria: 'C',
    musculos: ['cuerpo completo'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createJackAnalyzer,
  },
  {
    id: 'high_knees',
    nombre: 'Rodillas arriba',
    categoria: 'C',
    musculos: ['core', 'cuádriceps'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createHighKneeAnalyzer,
  },
  {
    id: 'butt_kicks',
    nombre: 'Talones al glúteo',
    categoria: 'C',
    musculos: ['isquiotibiales'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createButtKicksAnalyzer,
  },
  {
    id: 'mountain_climber',
    nombre: 'Escaladores',
    categoria: 'C',
    musculos: ['core', 'hombros'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createMountainClimberAnalyzer,
  },
  {
    id: 'burpee',
    nombre: 'Burpees',
    categoria: 'C',
    musculos: ['cuerpo completo'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createBurpeeAnalyzer,
  },
  {
    id: 'skater_jump',
    nombre: 'Saltos de patinador',
    categoria: 'C',
    musculos: ['glúteos', 'cuádriceps'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createSkaterJumpAnalyzer,
  },
  {
    id: 'seal_jack',
    nombre: 'Seal jacks',
    categoria: 'C',
    musculos: ['cuerpo completo'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createSealJackAnalyzer,
  },
  {
    id: 'crunch',
    nombre: 'Abdominales crunch',
    categoria: 'C',
    musculos: ['abdominales'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createCrunchAnalyzer,
  },
  {
    id: 'situp',
    nombre: 'Abdominales completos',
    categoria: 'C',
    musculos: ['abdominales'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createSitupAnalyzer,
  },
  {
    id: 'bicycle_crunch',
    nombre: 'Bicicleta',
    categoria: 'C',
    musculos: ['abdominales', 'oblicuos'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createBicycleCrunchAnalyzer,
  },
  {
    id: 'leg_raise',
    nombre: 'Elevación de piernas',
    categoria: 'C',
    musculos: ['abdominales'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createLegRaiseAnalyzer,
  },
  {
    id: 'flutter_kick',
    nombre: 'Patadas alternas',
    categoria: 'C',
    musculos: ['abdominales'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createFlutterKickAnalyzer,
  },
  {
    id: 'v_up',
    nombre: 'V-up',
    categoria: 'C',
    musculos: ['abdominales'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createVUpAnalyzer,
  },
  {
    id: 'russian_twist',
    nombre: 'Giro ruso',
    categoria: 'C',
    musculos: ['oblicuos'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createRussianTwistAnalyzer,
  },
  {
    id: 'toe_touch',
    nombre: 'Tocar puntas',
    categoria: 'C',
    musculos: ['abdominales'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createToeTouchAnalyzer,
  },
  {
    id: 'dead_bug',
    nombre: 'Bicho muerto',
    categoria: 'C',
    musculos: ['core'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createDeadBugAnalyzer,
  },
  {
    id: 'bird_dog',
    nombre: 'Perro de caza',
    categoria: 'C',
    musculos: ['core', 'espalda'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createBirdDogAnalyzer,
  },
  {
    id: 'superman',
    nombre: 'Superman',
    categoria: 'C',
    musculos: ['espalda', 'glúteos'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createSupermanAnalyzer,
  },
  {
    id: 'side_bend',
    nombre: 'Inclinación lateral',
    categoria: 'C',
    musculos: ['oblicuos'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createSideBendAnalyzer,
  },
  {
    id: 'pec_deck',
    nombre: 'Aperturas de pecho',
    categoria: 'C',
    musculos: ['pecho'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createPecDeckAnalyzer,
  },
  {
    id: 'dumbbell_fly',
    nombre: 'Aperturas con mancuernas',
    categoria: 'C',
    musculos: ['pecho'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createDumbbellFlyAnalyzer,
  },
  {
    id: 'shrug',
    nombre: 'Encogimientos de trapecio',
    categoria: 'C',
    musculos: ['trapecio'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createShrugAnalyzer,
  },
  {
    id: 'punch_cross',
    nombre: 'Golpes de boxeo',
    categoria: 'C',
    musculos: ['brazos', 'hombros'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createPunchCrossAnalyzer,
  },
  {
    id: 'jump_rope',
    nombre: 'Salto de cuerda',
    categoria: 'C',
    musculos: ['pantorrillas', 'hombros'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createJumpRopeAnalyzer,
  },
  {
    id: 'plank',
    nombre: 'Plancha',
    categoria: 'D',
    musculos: ['core'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createPlankAnalyzer,
  },
  {
    id: 'plank_forearm',
    nombre: 'Plancha en antebrazos',
    categoria: 'D',
    musculos: ['core'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createPlankForearmAnalyzer,
  },
  {
    id: 'plank_side',
    nombre: 'Plancha lateral',
    categoria: 'D',
    musculos: ['oblicuos', 'core'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: true,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createPlankSideAnalyzer,
  },
  {
    id: 'plank_reverse',
    nombre: 'Plancha inversa',
    categoria: 'D',
    musculos: ['core', 'glúteos'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createPlankReverseAnalyzer,
  },
  {
    id: 'hollow_hold',
    nombre: 'Hollow hold',
    categoria: 'D',
    musculos: ['core'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createHollowHoldAnalyzer,
  },
  {
    id: 'wall_sit',
    nombre: 'Sentadilla isométrica en pared',
    categoria: 'D',
    musculos: ['cuádriceps'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createWallSitAnalyzer,
  },
  {
    id: 'squat_hold',
    nombre: 'Sentadilla sostenida',
    categoria: 'D',
    musculos: ['cuádriceps', 'glúteos'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createSquatHoldAnalyzer,
  },
  {
    id: 'glute_bridge_hold',
    nombre: 'Puente de glúteos sostenido',
    categoria: 'D',
    musculos: ['glúteos'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createGluteBridgeHoldAnalyzer,
  },
  {
    id: 'dead_hang',
    nombre: 'Colgarse de la barra',
    categoria: 'D',
    musculos: ['dorsales', 'bíceps'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createDeadHangAnalyzer,
  },
  {
    id: 'chin_hold',
    nombre: 'Isométrico de dominada',
    categoria: 'D',
    musculos: ['dorsales', 'bíceps'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createChinHoldAnalyzer,
  },
  {
    id: 'superman_hold',
    nombre: 'Superman sostenido',
    categoria: 'D',
    musculos: ['espalda', 'glúteos'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createSupermanHoldAnalyzer,
  },
  {
    id: 'bird_dog_hold',
    nombre: 'Perro de caza sostenido',
    categoria: 'D',
    musculos: ['core'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createBirdDogHoldAnalyzer,
  },
  {
    id: 'boat_pose',
    nombre: 'Postura del bote',
    categoria: 'D',
    musculos: ['core'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createBoatPoseAnalyzer,
  },
  {
    id: 'l_sit',
    nombre: 'L-sit',
    categoria: 'D',
    musculos: ['core', 'tríceps'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createLSitAnalyzer,
  },
  {
    id: 'chair_pose',
    nombre: 'Postura de la silla',
    categoria: 'D',
    musculos: ['cuádriceps'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createChairPoseAnalyzer,
  },
  {
    id: 'st_hamstring',
    nombre: 'Isquiotibiales',
    categoria: 'E',
    musculos: ['isquiotibiales'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStHamstringAnalyzer,
  },
  {
    id: 'st_quad',
    nombre: 'Cuádriceps de pie',
    categoria: 'E',
    musculos: ['cuádriceps'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: true,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStQuadAnalyzer,
  },
  {
    id: 'st_calf_wall',
    nombre: 'Pantorrilla contra pared',
    categoria: 'E',
    musculos: ['pantorrillas'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStCalfWallAnalyzer,
  },
  {
    id: 'st_hip_flexor',
    nombre: 'Flexor de cadera',
    categoria: 'E',
    musculos: ['flexores de cadera'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStHipFlexorAnalyzer,
  },
  {
    id: 'st_pigeon',
    nombre: 'Paloma',
    categoria: 'E',
    musculos: ['glúteos', 'piriforme'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: true,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createStPigeonAnalyzer,
  },
  {
    id: 'st_figure4',
    nombre: 'Figura 4',
    categoria: 'E',
    musculos: ['glúteos', 'piriforme'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: true,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStFigure4Analyzer,
  },
  {
    id: 'st_butterfly',
    nombre: 'Mariposa',
    categoria: 'E',
    musculos: ['aductores'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStButterflyAnalyzer,
  },
  {
    id: 'st_frog',
    nombre: 'Rana',
    categoria: 'E',
    musculos: ['aductores'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createStFrogAnalyzer,
  },
  {
    id: 'st_cobra',
    nombre: 'Cobra',
    categoria: 'E',
    musculos: ['abdominales', 'lumbar'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStCobraAnalyzer,
  },
  {
    id: 'st_childs_pose',
    nombre: 'Postura del niño',
    categoria: 'E',
    musculos: ['espalda', 'lumbar'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStChildsPoseAnalyzer,
  },
  {
    id: 'st_cat_cow',
    nombre: 'Gato-vaca',
    categoria: 'E',
    musculos: ['espalda'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStCatCowAnalyzer,
  },
  {
    id: 'st_downdog',
    nombre: 'Perro boca abajo',
    categoria: 'E',
    musculos: ['isquiotibiales', 'hombros'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStDowndogAnalyzer,
  },
  {
    id: 'st_shoulder_cross',
    nombre: 'Deltoides',
    categoria: 'E',
    musculos: ['hombros'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: true,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStShoulderCrossAnalyzer,
  },
  {
    id: 'st_triceps',
    nombre: 'Tríceps sobre la cabeza',
    categoria: 'E',
    musculos: ['tríceps'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: true,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStTricepsAnalyzer,
  },
  {
    id: 'st_chest_door',
    nombre: 'Pectoral en puerta',
    categoria: 'E',
    musculos: ['pecho'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: true,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStChestDoorAnalyzer,
  },
  {
    id: 'st_lat',
    nombre: 'Dorsal',
    categoria: 'E',
    musculos: ['dorsales'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: true,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStLatAnalyzer,
  },
  {
    id: 'st_neck_side',
    nombre: 'Cuello lateral',
    categoria: 'E',
    musculos: ['cuello'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: true,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStNeckSideAnalyzer,
  },
  {
    id: 'st_spinal_twist',
    nombre: 'Torsión espinal sentado',
    categoria: 'E',
    musculos: ['espalda'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStSpinalTwistAnalyzer,
  },
  {
    id: 'st_side_bend',
    nombre: 'Inclinación lateral de pie',
    categoria: 'E',
    musculos: ['oblicuos'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStSideBendAnalyzer,
  },
  {
    id: 'st_standing_forward',
    nombre: 'Flexión adelante de pie',
    categoria: 'E',
    musculos: ['isquiotibiales'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createStStandingForwardAnalyzer,
  },
  {
    id: 'wu_arm_circles',
    nombre: 'Círculos de brazos',
    categoria: 'F',
    musculos: ['hombros'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createWuArmCirclesAnalyzer,
  },
  {
    id: 'wu_hip_circles',
    nombre: 'Círculos de cadera',
    categoria: 'F',
    musculos: ['cadera'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createWuHipCirclesAnalyzer,
  },
  {
    id: 'wu_torso_twist',
    nombre: 'Rotación de torso',
    categoria: 'F',
    musculos: ['oblicuos'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createWuTorsoTwistAnalyzer,
  },
  {
    id: 'wu_leg_swing',
    nombre: 'Balanceo de piernas',
    categoria: 'F',
    musculos: ['cadera', 'isquiotibiales'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: true,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createWuLegSwingAnalyzer,
  },
  {
    id: 'wu_inchworm',
    nombre: 'Gusano',
    categoria: 'F',
    musculos: ['cuerpo completo'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createWuInchwormAnalyzer,
  },
  {
    id: 'wu_worlds_greatest',
    nombre: "World's greatest",
    categoria: 'F',
    musculos: ['cuerpo completo'],
    tipo: 'reps',
    vistaCamara: 'lateral',
    unilateral: false,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createWuWorldsGreatestAnalyzer,
  },
  {
    id: 'wu_shoulder_dislocate',
    nombre: 'Pase de hombros',
    categoria: 'F',
    musculos: ['hombros'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createWuShoulderDislocateAnalyzer,
  },
  {
    id: 'wu_march',
    nombre: 'Marcha en el lugar',
    categoria: 'F',
    musculos: ['cuádriceps', 'cadera'],
    tipo: 'reps',
    vistaCamara: 'frontal',
    unilateral: false,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createWuMarchAnalyzer,
  },
  {
    id: 'bal_single_leg',
    nombre: 'Equilibrio a una pierna',
    categoria: 'G',
    musculos: ['pantorrillas', 'core'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: true,
    dificultad: 'principiante',
    estado: 'implementado',
    analyzerFactory: createBalSingleLegAnalyzer,
  },
  {
    id: 'bal_tree',
    nombre: 'Postura del árbol',
    categoria: 'G',
    musculos: ['pantorrillas', 'core'],
    tipo: 'tiempo',
    vistaCamara: 'frontal',
    unilateral: true,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createBalTreeAnalyzer,
  },
  {
    id: 'bal_warrior3',
    nombre: 'Guerrero III',
    categoria: 'G',
    musculos: ['core', 'glúteos'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: true,
    dificultad: 'avanzado',
    estado: 'implementado',
    analyzerFactory: createBalWarrior3Analyzer,
  },
  {
    id: 'bal_standing_quad',
    nombre: 'Equilibrio con cuádriceps',
    categoria: 'G',
    musculos: ['cuádriceps', 'core'],
    tipo: 'tiempo',
    vistaCamara: 'lateral',
    unilateral: true,
    dificultad: 'intermedio',
    estado: 'implementado',
    analyzerFactory: createBalStandingQuadAnalyzer,
  },
]

const registryMap = new Map()
for (const exercise of EXERCISE_REGISTRY) {
  registryMap.set(exercise.id, exercise)
}

export function getExerciseById(id) {
  return registryMap.get(id) || null
}

export function getExercisesByCategory(category) {
  return EXERCISE_REGISTRY.filter((ex) => ex.categoria === category)
}

export function getExercisesByMuscle(muscle) {
  return EXERCISE_REGISTRY.filter((ex) =>
    ex.musculos.some((m) => m.toLowerCase().includes(muscle.toLowerCase()))
  )
}

export function getExercisesByDifficulty(dificultad) {
  return EXERCISE_REGISTRY.filter((ex) => ex.dificultad === dificultad)
}

export function getExercisesByTipo(tipo) {
  return EXERCISE_REGISTRY.filter((ex) => ex.tipo === tipo)
}

export function getImplementedExercises() {
  return EXERCISE_REGISTRY.filter((ex) => ex.estado === 'implementado')
}

export function searchExercises(query) {
  const q = query.toLowerCase().trim()
  if (!q) return EXERCISE_REGISTRY
  return EXERCISE_REGISTRY.filter(
    (ex) =>
      ex.nombre.toLowerCase().includes(q) ||
      ex.musculos.some((m) => m.toLowerCase().includes(q))
  )
}

export function createAnalyzerForExercise(id) {
  const exercise = registryMap.get(id)
  if (!exercise) return null
  if (exercise.analyzerFactory) return exercise.analyzerFactory()
  return null
}
