-- Módulo de recepción: catálogo POS, ventas y gastos operativos.
-- La cuenta de recepción puede vender y registrar gastos; solo admin mantiene
-- el catálogo y el inventario.

create table if not exists public.pos_products (
  id uuid primary key default gen_random_uuid(),
  nombre text not null unique check (length(trim(nombre)) between 1 and 100),
  costo_compra numeric(10, 2) not null default 0 check (costo_compra >= 0),
  precio numeric(10, 2) not null check (precio > 0),
  stock integer not null default 0 check (stock >= 0),
  stock_minimo integer not null default 0 check (stock_minimo >= 0),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pos_sales (
  id uuid primary key default gen_random_uuid(),
  cashier_id uuid not null references auth.users (id),
  metodo_pago text not null check (metodo_pago in ('qr', 'efectivo', 'transferencia', 'tarjeta', 'yape_plin')),
  total numeric(12, 2) not null check (total > 0),
  receipt_number bigint generated by default as identity unique,
  created_at timestamptz not null default now()
);

create index if not exists idx_pos_sales_created_at on public.pos_sales (created_at);

create table if not exists public.pos_sale_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.pos_sales (id) on delete cascade,
  product_id uuid not null references public.pos_products (id),
  product_name text not null,
  unit_price numeric(10, 2) not null check (unit_price > 0),
  quantity integer not null check (quantity > 0),
  line_total numeric(12, 2) not null check (line_total > 0)
);

create index if not exists idx_pos_sale_items_sale on public.pos_sale_items (sale_id);

create table if not exists public.operating_expenses (
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null default auth.uid() references auth.users (id),
  concepto text not null check (length(trim(concepto)) between 1 and 160),
  categoria text not null check (categoria in ('Sueldos', 'Alquiler', 'Servicios', 'Insumos', 'Mantenimiento', 'Otros')),
  metodo_pago text not null default 'efectivo' check (metodo_pago in ('qr', 'efectivo', 'transferencia', 'tarjeta', 'yape_plin')),
  monto numeric(12, 2) not null check (monto > 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_operating_expenses_created_at
  on public.operating_expenses (created_at);

alter table public.pos_products enable row level security;
alter table public.pos_sales enable row level security;
alter table public.pos_sale_items enable row level security;
alter table public.operating_expenses enable row level security;

drop policy if exists "Staff puede leer productos POS" on public.pos_products;
create policy "Staff puede leer productos POS"
  on public.pos_products for select
  to authenticated
  using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in
      ('recepcion@ironforge.com', 'admin@ironforge.com')
  );

drop policy if exists "Admin gestiona productos POS" on public.pos_products;
create policy "Admin gestiona productos POS"
  on public.pos_products for all
  to authenticated
  using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'admin@ironforge.com')
  with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'admin@ironforge.com');

drop policy if exists "Staff puede leer ventas POS" on public.pos_sales;
create policy "Staff puede leer ventas POS"
  on public.pos_sales for select
  to authenticated
  using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in
      ('recepcion@ironforge.com', 'admin@ironforge.com')
  );

drop policy if exists "Staff puede leer detalle de ventas POS" on public.pos_sale_items;
create policy "Staff puede leer detalle de ventas POS"
  on public.pos_sale_items for select
  to authenticated
  using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in
      ('recepcion@ironforge.com', 'admin@ironforge.com')
  );

drop policy if exists "Staff puede leer gastos operativos" on public.operating_expenses;
create policy "Staff puede leer gastos operativos"
  on public.operating_expenses for select
  to authenticated
  using (
    lower(coalesce(auth.jwt() ->> 'email', '')) in
      ('recepcion@ironforge.com', 'admin@ironforge.com')
  );

drop policy if exists "Staff puede registrar gastos operativos" on public.operating_expenses;
create policy "Staff puede registrar gastos operativos"
  on public.operating_expenses for insert
  to authenticated
  with check (
    (created_by is null or auth.uid() = created_by)
    and lower(coalesce(auth.jwt() ->> 'email', '')) in
      ('recepcion@ironforge.com', 'admin@ironforge.com')
  );

create or replace function public.register_pos_sale(
  p_payment_method text,
  p_items jsonb
)
returns public.pos_sales
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  v_sale public.pos_sales;
  v_item jsonb;
  v_product public.pos_products;
  v_quantity integer;
  v_total numeric(12, 2) := 0;
begin
  if v_email not in ('recepcion@ironforge.com', 'admin@ironforge.com')
     or auth.uid() is null then
    raise exception 'Solo recepción o administración puede registrar ventas';
  end if;
  if p_payment_method not in ('qr', 'efectivo', 'transferencia', 'tarjeta', 'yape_plin') then
    raise exception 'Método de pago no válido';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'La venta debe incluir al menos un producto';
  end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    if jsonb_typeof(v_item -> 'quantity') <> 'number'
       or (v_item ->> 'quantity') !~ '^[0-9]+$' then
      raise exception 'La cantidad de cada producto debe ser un entero positivo';
    end if;
    v_quantity := (v_item ->> 'quantity')::integer;
    if v_quantity < 1 then
      raise exception 'La cantidad de cada producto debe ser un entero positivo';
    end if;
    select * into v_product
      from public.pos_products
     where id = (v_item ->> 'product_id')::uuid
       and activo = true
     for update;
    if not found then
      raise exception 'Uno de los productos no existe o está inactivo';
    end if;
    if v_product.stock < v_quantity then
      raise exception 'Stock insuficiente para el producto %', v_product.nombre;
    end if;
    v_total := v_total + (v_product.precio * v_quantity);
  end loop;

  insert into public.pos_sales (cashier_id, metodo_pago, total)
  values (auth.uid(), p_payment_method, v_total)
  returning * into v_sale;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := (v_item ->> 'quantity')::integer;
    select * into v_product
      from public.pos_products
     where id = (v_item ->> 'product_id')::uuid
       and activo = true;
    insert into public.pos_sale_items (
      sale_id, product_id, product_name, unit_price, quantity, line_total
    )
    values (
      v_sale.id, v_product.id, v_product.nombre, v_product.precio,
      v_quantity, v_product.precio * v_quantity
    );
    update public.pos_products
       set stock = stock - v_quantity,
           updated_at = now()
     where id = v_product.id;
  end loop;

  return v_sale;
end;
$$;

revoke all on function public.register_pos_sale(text, jsonb) from anon;
revoke all on function public.register_pos_sale(text, jsonb) from public;
grant execute on function public.register_pos_sale(text, jsonb) to authenticated;
